[Settings]
source_file = config/user_demo.txt
final_file = output/user_result.txt
# 接口最小分辨率，需要开启 open_filter_resolution 才能生效 | Minimum resolution of the interface, need to enable open_filter_resolution to take effect
min_resolution = 1920x1080
